theme: jekyll-theme-minimal
title: Sam Sinai
description: Co-founder and Head of Machine Learning at Dyno Therapeutics, working on algorithmic approaches to the discovery of novelty in biology.
logo: ./images/me.jpg
google_analytics: G-QGEFC306V1
